version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"